apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
 - repo: oci://quay.io/jetstack/charts/
   version: 1.19.2
   name: cert-manager
   includeCRDs: true

resources:
  - issuer.yaml
  - secrets/cloudflare.yaml
