apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

# I have this setup for some private data such as emails for the issuer, not ideal setup though
resources:
  - git@github.com:tallen12/private_k3s_configs.git/infrastructure/cert-manager/local