apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
bases:
  - ../base

resources:
  - git@github.com:tallen12/private_k3s_configs.git/infrastructure/cert-manager/local