apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
  - repo: https://1password.github.io/connect-helm-charts
    version: 2.3.0
    name: connect
    releaseName: one-password-connect
    namespace: external-secrets
    valuesInline:
      connect:
        serviceType: ClusterIP

resources:
  - cluster_secret_store.yaml
