apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets


resources:
  - https://raw.githubusercontent.com/external-secrets/external-secrets/<replace_with_your_version>/deploy/crds/bundle.yaml
  - namespace.yaml
  - external-secrets
  - 1password