apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

helmCharts:
  - repo: https://charts.external-secrets.io
    version: 2.0.0
    name: external-secrets
    releaseName: external-secrets
    includeCRDs: true
    namespace: external-secrets

resources:
  - namespace.yaml
  - 1password