apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secret

helmCharts:
  - repo: https://charts.external-secrets.io
    version: 2.0.0
    name: external-secrets
    releaseName: external-secrets
    includeCRDs: true        

resources:
  - 1password