apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/namespace.yaml
- github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.4.1
- base/base.yaml
- base/istiod.yaml
- base/cni.yaml
- base/ztunnel.yaml

patches:
  - target:
      namespace: argocd
      name: istio.*
    path: patch.yaml
