apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- secrets/git_key.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: config_map_patch.yaml
    target:
      namespace: argocd
      name: argocd-cm
