apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - patch: |-
      - op: replace
        path: /data/kustomize.buildOptions
        value: "--enable-helm"
    target:
      kind: ConfigMap
      name: argocd-cm
  # - path: config_map_patch.yaml
  #   target:
  #     kind: ConfigMap
  #     name: argocd-cm
